  version: '3'
  services:
    app:
      build: .
      environment:
        TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION}
        S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}